### ISSUE TITLE
تعديل ملفات ال freesat.py 

### ISSUE THREAD

**Issue by angelheart150** [zKhadiri/Epg-plugin#149]
السلام عليكم ورحمة الله وبركاته

اخي العزيز الفاضل زكريا أخي المطور الكبير أ. حسين أتمني أن تكونا فى أفضل حال وكل الأخوة المطورين المشاركين فى البلجن   @fairbird  @zKhadiri 

- هذا تعديلي على ملف freesat.py ل provider بلجن epggrabber على قدر علمي المتواضع 
تم تحديث كل قنوات ال api وتعمل الان بشكل ممتاز على بايثون 2 و 3 وحجم الملف المحمل تجاوز 8 ميجا وهو كم هائل للقنوات ودليل برامجها
المشكلة الوحيده التى تواجهني احيانا واعتقد انها من سيرفر التنزيل هي 
 Error processing data: No JSON object could be decoded
 مرفق الملف المعدل ونتيجة التحميل 

[النتيجة.txt](https://github.com/user-attachments/files/18239063/default.txt)
[freesat.zip](https://github.com/user-attachments/files/18239036/freesat.zip)

- حاولت تعديل ملف lovenature ولكن الموقع به مشاكل ويوجد موقع ممتاز عليه الدليل لمدة 8 ايام ولكن خبرتي ضعيفة فى html 
الموقع هو  [https://www.mytvsuper.com/en/epg/403/Love-Nature-4K/](url)
 
- ومشكلة قناة   DSTV  هنا موقعها 
[https://www.dstv.com/en-za/explore/tv-guide](url)
اعلم انك مشغول وكان الله فى عونك وهدفي من التعديل مساعدتك وتطوير البلجن جزاك الله والاخ حسين المحترم خيرا الجزاء 
اخوك محمد الصفطي - مصر

هذه مشاكل الملفات التى اتمني ان يعاد بناءها من جديد

root@amikoalien:~# python /usr/lib/enigma2/python/Plugins/Extensions/EPGGrabber/provide                                                        rs/caf.py
**************Canal+AF EPG******************
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Plugins/Extensions/EPGGrabber/providers/caf.py", line 59, in <module>
    main()
  File "/usr/lib/enigma2/python/Plugins/Extensions/EPGGrabber/providers/caf.py", line 51, in main
    xml_header(EPG_ROOT + '/caf.xml', channels)
  File "/usr/lib/enigma2/python/Plugins/Extensions/EPGGrabber/core/header.py", line 18, in xml_header
    for channel in channels:
TypeError: 'NoneType' object is not iterable

==================================================================================

root@amikoalien:~# python /usr/lib/enigma2/python/Plugins/Extensions/EPGGrabber/providers/dstv.py
**************DSTV EPG******************
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Plugins/Extensions/EPGGrabber/providers/dstv.py", line 99, in <module>
    main()
  File "/usr/lib/enigma2/python/Plugins/Extensions/EPGGrabber/providers/dstv.py", line 70, in main
    dstv()
  File "/usr/lib/enigma2/python/Plugins/Extensions/EPGGrabber/providers/dstv.py", line 41, in dstv
    data = json.loads(link.text)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads

  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
ValueError: No JSON object could be decoded

==================================================================================

root@amikoalien:~# python /usr/lib/enigma2/python/Plugins/Extensions/EPGGrabber/providers/lematin.py
**************LE MATIN EPG******************
**************FINISHED******************

==================================================================================

root@amikoalien:~# python /usr/lib/enigma2/python/Plugins/Extensions/EPGGrabber/providers/lovenature.py
**************Love Nature EPG******************
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Plugins/Extensions/EPGGrabber/providers/lovenature.py", line 91, in <module>
    main()
  File "/usr/lib/enigma2/python/Plugins/Extensions/EPGGrabber/providers/lovenature.py", line 80, in main
    guide()
  File "/usr/lib/enigma2/python/Plugins/Extensions/EPGGrabber/providers/lovenature.py", line 51, in guide
    if datetime.strptime(key,"%Y-%m-%d").date() >= date.today():
  File "/usr/lib/python2.7/_strptime.py", line 332, in _strptime
ValueError: time data 'message' does not match format '%Y-%m-%d'

==================================================================================

root@amikoalien:~# python /usr/lib/enigma2/python/Plugins/Extensions/EPGGrabber/providers/mbc.py
**************MBC EPG******************
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Plugins/Extensions/EPGGrabber/providers/mbc.py", line 176, in <module>
    main()
  File "/usr/lib/enigma2/python/Plugins/Extensions/EPGGrabber/providers/mbc.py", line 163, in main
    mbc()
  File "/usr/lib/enigma2/python/Plugins/Extensions/EPGGrabber/providers/mbc.py", line 70, in mbc
    data = json.loads(link.text)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads

  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
ValueError: No JSON object could be decoded

==================================================================================

root@amikoalien:~# python /usr/lib/enigma2/python/Plugins/Extensions/EPGGrabber/providers/satTv.py
**************SatTv EPG******************
No JSON object could be decoded
**************FINISHED******************

==================================================================================

root@amikoalien:~# python /usr/lib/enigma2/python/Plugins/Extensions/EPGGrabber/providers/satTvB.py
**************SAT Tv backup EPG******************
Downloading SAT Tv guide
Please wait....
--2024-12-23 03:05:50--  http://ipkinstall.ath.cx/EPG/satTv/satTv.xml
Resolving ipkinstall.ath.cx... 41.200.35.71
Connecting to ipkinstall.ath.cx|41.200.35.71|:80... ^Cchanging to your timezone please wait....
file is empty
satTv.xml donwloaded with success
**************FINISHED******************

========================================================================

**************Snrt EPG******************
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Plugins/Extensions/EPGGrabber/providers/snrt.py", line 96, in <module>
    main()
  File "/usr/lib/enigma2/python/Plugins/Extensions/EPGGrabber/providers/snrt.py", line 87, in main
    arryadia()
  File "/usr/lib/enigma2/python/Plugins/Extensions/EPGGrabber/providers/snrt.py", line 46, in arryadia
    for start, end, t, d, lv in zip(start_dt, start_dt[1:] + [start_dt[0]], titles, descriptions, live):
IndexError: list index out of range

==================================================================================

root@amikoalien:~# python /usr/lib/enigma2/python/Plugins/Extensions/EPGGrabber/providers/sony.py
**************Indian sports channels EPG******************
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Plugins/Extensions/EPGGrabber/providers/sony.py", line 95, in <module>
    main()
  File "/usr/lib/enigma2/python/Plugins/Extensions/EPGGrabber/providers/sony.py", line 77, in main
    sony()
  File "/usr/lib/enigma2/python/Plugins/Extensions/EPGGrabber/providers/sony.py", line 20, in sony
    url = s.get('https://www.peotv.com/tvguide/channel/' + code)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.peotv.com', port=443): Max retries exceeded with url: /tvguide/channel/sony-six/84 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

==================================================================================

root@amikoalien:~# python /usr/lib/enigma2/python/Plugins/Extensions/EPGGrabber/providers/aljazeera.py
Ip blocked , using proxy....
Please wait this might take a while.
('Error occurred. Retry!!', 3)
('Error occurred. Retry!!', 2)
('Error occurred. Retry!!', 1)
('Error occurred. Retry!!', 0)
**************FINISHED******************
==================================================================================

**Comment by fairbird** [comment]
هذه الأخطاء تحتاج الى مناقشة ومتابعة والأفضل تكون في المنتدى مباشرة صعب هنا مناقشتها في السورس .. هناك سوف يتدخل الجميع للمحاولة بالمساعدة في هذا الوضوع
[مشاكل وأسئلة برمجة وتطوير الاضافات والسكين وبناء الصور للانيجما](https://www.tunisia-sat.com/forums/threads/3827857/)

**Comment by angelheart150** [comment]
> هذه الأخطاء تحتاج الى مناقشة ومتابعة والأفضل تكون في المنتدى مباشرة صعب هنا مناقشتها في السورس .. هناك سوف يتدخل الجميع للمحاولة بالمساعدة في موضوع البلجن مباشرة .. ضع رد هناك مع ما ذكرته هنا ...

قمت بعمل ما طلبت استاذ حسين اذا رغبت فى حذف ال issue  تفضل بحذفه لعدم حدوث التباس . تحياتي .
